/**
 * Outbound daemon <-> control-plane frames (ZOS-96).
 *
 * These are the wire frames on the daemon's OUTBOUND WebSocket to the
 * control plane — the machine-connectivity channel. Employee machines never
 * expose an inbound port; the daemon dials the control plane and stays
 * connected (heartbeat, reconnect with registration replay, watermark
 * catch-up). correlationId is generated by the control plane for inbound
 * commands (and by the daemon for machine-initiated requests); machineId
 * scopes a channel; watermark is the daemon's last-acked command sequence
 * so reconnects can replay anything missed.
 *
 * Direction convention: the control plane pushes `rpc.request` frames to the
 * daemon (commands it must execute); the daemon answers with `rpc.response`
 * and an `ack` once it has started/handled the command. The daemon may also
 * initiate `rpc.request` frames upward. One correlation namespace per
 * direction is fine — ids are UUIDs, globally unique (AC: uniqueness across
 * connections).
 */
import type { Schema } from "./schema.ts";
import { ok, fail } from "./result.ts";
import { missingField, invalidField } from "./errors.ts";
import { object, string, nonEmptyString, number, boolean, optional, record, array } from "./schema.ts";

export const HELLO = "cowork.v1.control.hello";
export const RPC_REQUEST = "cowork.v1.control.rpc.request";
export const RPC_RESPONSE = "cowork.v1.control.rpc.response";
export const ACK = "cowork.v1.control.ack";
export const PING = "cowork.v1.control.ping";
export const PONG = "cowork.v1.control.pong";
export const WATERMARK = "cowork.v1.control.watermark";

/**
 * WebSocket close codes on the machine channel (ZOS-91). Numeric codes so the
daemon and the plane read the same constant, not a stringly-typed guess.
 *
 * 4003 — the machine's identity is revoked; the daemon must stop reconnecting.
 * 4004 — another live connection already holds this machine id.
 */
export const CLOSE_MACHINE_REVOKED = 4003;
export const CLOSE_DUPLICATE_MACHINE = 4004;

export const CONTROL_TAGS = [HELLO, RPC_REQUEST, RPC_RESPONSE, ACK, PING, PONG, WATERMARK] as const;

/** One harness this machine can run (mirrors `AdapterManifest`, additive). */
export interface AdapterDescriptorFrame {
  id: string;
  name?: string;
  protocolVersion?: number;
  capabilities?: Array<{ name: string; version?: number }>;
}

/**
 * What a machine can do (ZOS-91). Every field is optional and unknown keys are
 * ignored, so a newer daemon (more fields) still registers with an older plane
 * and vice versa. `manifestVersion` moves only for a breaking change.
 */
export interface MachineManifestFrame {
  manifestVersion?: number;
  platform?: string;
  arch?: string;
  hostname?: string;
  daemonVersion?: string;
  node?: string;
  adapters?: AdapterDescriptorFrame[];
  services?: string[];
}

export interface HelloFrame {
  machineId: string;
  name: string;
  version: number;
  /** Last command sequence the machine handled; control plane replays above it. */
  watermark: number;
  /** ZOS-91 capability manifest — additive, absent on older daemons. */
  manifest?: MachineManifestFrame;
}

export interface RpcRequestFrame {
  correlationId: string;
  method: string;
  params?: Record<string, unknown>;
  timeoutMs?: number;
}

export interface RpcErrorFrame {
  code: string;
  message: string;
}

export interface RpcResponseFrame {
  correlationId: string;
  ok: boolean;
  data?: unknown;
  error?: RpcErrorFrame;
}

export interface AckFrame {
  correlationId: string;
}

export interface WatermarkFrame {
  watermark: number;
}

export interface PingFrame {}
export interface PongFrame {}

const adapterCapabilityFrame: Schema<{ name: string; version?: number }> = object({
  name: nonEmptyString("capabilities[].name"),
  version: optional(number("capabilities[].version")),
});

const adapterDescriptorFrame: Schema<AdapterDescriptorFrame> = object({
  id: nonEmptyString("id"),
  name: optional(string("name")),
  protocolVersion: optional(number("protocolVersion")),
  capabilities: optional(array(adapterCapabilityFrame)),
});

/** Additive manifest validator — tolerate partial payloads and unknown keys. */
export const machineManifest: Schema<MachineManifestFrame> = object({
  manifestVersion: optional(number("manifestVersion")),
  platform: optional(string("platform")),
  arch: optional(string("arch")),
  hostname: optional(string("hostname")),
  daemonVersion: optional(string("daemonVersion")),
  node: optional(string("node")),
  adapters: optional(array(adapterDescriptorFrame)),
  services: optional(array(string("services[]"))),
});

export const hello: Schema<HelloFrame> = object({
  machineId: nonEmptyString("machineId"),
  name: string("name"),
  version: number("version"),
  watermark: number("watermark"),
  manifest: optional(machineManifest),
});

export const rpcRequest: Schema<RpcRequestFrame> = object({
  correlationId: nonEmptyString("correlationId"),
  method: nonEmptyString("method"),
  params: optional(record()),
  timeoutMs: optional(number("timeoutMs")),
});

export const rpcError: Schema<RpcErrorFrame> = object({
  code: nonEmptyString("code"),
  message: string("message"),
});

export const rpcResponse: Schema<RpcResponseFrame> = object({
  correlationId: nonEmptyString("correlationId"),
  ok: boolean("ok"),
  data: optional(record()),
  error: optional(rpcError),
});

export const ack: Schema<AckFrame> = object({
  correlationId: nonEmptyString("correlationId"),
});

const nonNegativeInt: Schema<number> = (input) => {
  if (input === undefined) return fail(missingField("watermark"));
  if (typeof input !== "number" || !Number.isInteger(input) || input < 0) {
    return fail(invalidField("watermark", "non-negative integer"));
  }
  return ok(input);
};

export const watermark: Schema<WatermarkFrame> = object({
  watermark: nonNegativeInt,
});

export const ping: Schema<PingFrame> = object({});
export const pong: Schema<PongFrame> = object({});

/** Frame-level discrimination: tag -> payload validator. */
export const FRAME_VALIDATORS: Record<string, Schema<unknown>> = {
  [HELLO]: hello,
  [RPC_REQUEST]: rpcRequest,
  [RPC_RESPONSE]: rpcResponse,
  [ACK]: ack,
  [PING]: ping,
  [PONG]: pong,
  [WATERMARK]: watermark,
};

export const isControlTag = (tag: string): boolean => (CONTROL_TAGS as readonly string[]).includes(tag);