import { Download, Share2 } from "lucide-react";
import { useCallback, useRef, useState } from "react";

interface Message {
	role: string;
	content: string;
	timestamp: number;
	model?: string;
	provider?: string;
}

interface ShareExportProps {
	messages: Message[];
}

function formatMessagesAsMarkdown(messages: Message[]): string {
	const lines: string[] = [];
	lines.push("# Zosma Cowork Conversation");
	lines.push("");
	lines.push(
		`> Exported on ${new Date().toLocaleDateString([], {
			year: "numeric",
			month: "long",
			day: "numeric",
		})}`,
	);
	lines.push("");
	lines.push("---");
	lines.push("");

	for (const msg of messages) {
		const role = msg.role === "user" ? "You" : "Zosma";
		const modelTag = msg.model ? ` (${msg.provider}/${msg.model})` : "";
		lines.push(`### **${role}:**${modelTag}`);
		lines.push("");
		lines.push(msg.content);
		lines.push("");
	}

	lines.push("---");
	lines.push("_Generated by [Zosma Cowork](https://github.com/zosmaai/zosma-cowork)_");

	return lines.join("\n");
}

export function ShareExport({ messages }: ShareExportProps) {
	const [copiedExport, setCopiedExport] = useState(false);
	const [copiedShare, setCopiedShare] = useState(false);
	const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);

	const showCopied = useCallback((type: "export" | "share") => {
		if (type === "export") setCopiedExport(true);
		else setCopiedShare(true);
		if (timerRef.current) clearTimeout(timerRef.current);
		timerRef.current = setTimeout(() => {
			setCopiedExport(false);
			setCopiedShare(false);
		}, 2000);
	}, []);

	const handleExport = useCallback(async () => {
		const markdown = formatMessagesAsMarkdown(messages);
		try {
			await navigator.clipboard.writeText(markdown);
			showCopied("export");
		} catch {
			// Clipboard not available
		}
	}, [messages, showCopied]);

	const handleShare = useCallback(async () => {
		try {
			await navigator.clipboard.writeText("https://github.com/zosmaai/zosma-cowork");
			showCopied("share");
		} catch {
			// Clipboard not available
		}
	}, [showCopied]);

	return (
		<div className="flex items-center gap-1">
			{messages.length > 0 && (
				<button
					type="button"
					title="Export conversation"
					onClick={handleExport}
					className="flex items-center gap-1 rounded px-1.5 py-1 text-[11px] text-muted-foreground hover:text-foreground hover:bg-muted/60 transition-colors"
				>
					<Download size={12} />
					{copiedExport ? "Copied!" : "Export"}
				</button>
			)}
			<button
				type="button"
				title="Share Zosma Cowork"
				onClick={handleShare}
				className="flex items-center gap-1 rounded px-1.5 py-1 text-[11px] text-muted-foreground hover:text-foreground hover:bg-muted/60 transition-colors"
			>
				<Share2 size={12} />
				{copiedShare ? "Copied!" : "Share"}
			</button>
		</div>
	);
}
